CREATE TABLE IF NOT EXISTS pages
(
    id
    CHAR
(
    36
) PRIMARY KEY,
    title VARCHAR
(
    255
) NOT NULL,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    );
